### PR TITLE
chore: semantic-release config update

### PR DESCRIPTION
**Pull request by megheaiulian**
semantic-release config update

### CODE REVIEW

**Comment by cristinecula** [comment]
@megheaiulian is this a recent addition to the semantic-release tool? We should update all components with this bit.

**Comment by megheaiulian** [comment]
@cristinecula It seems the default preset is `angular` which does not use `!` for a breaking change and has a few other differences.  If we lint commit using `conventionalcommits` format we should also use it for `semantic-release`. Maybe the default has changed between versions?

**Comment by cristinecula** [comment]
Probably...

**Comment by nomego** [comment]
Or should we just switch to gitmoji? :D

**Comment by cristinecula** [comment]
:sparkles:

**Pull request merged**
