### PR TITLE
38 - Update to Polymer 2.x - part 1

### PR DESCRIPTION
**Pull request by dotpointer**
Update to Polymer 2.x - part 1.

* Upgrade Polymer CLI to 1.8.
* Regenerated yarn.lock and package-lock.json.
* Adding .nvmrc.
* Updated test settings, headless.
* Removing local Firefox test due to geckodriver issue.
* Adding Sauce Labs configuration.
* Updated yarn steps for package-lock.json.

Issue is #38.

### CODE REVIEW

**Comment by Wurper** [comment]
Any idea for the travis errors?

**Comment by nomego** [comment]
Wow interesting! It seems like when we run the component in "native" 2.x, there is some missing part to html import polyfilling on ms edge and iOS Safari. This is probably the same importLink issue we see in the prodlogs from iPads. Maybe @megheaiulian has some idea on how to fix this, but it's a real issue (that we've had for a long time).

**Comment by nomego** [comment]
> that's not polyfilled because it's inserted at runtime
> all that code needs to be updated to use importHref
> assign that PR to me I'll fix and update today

from @megheaiulian

**Comment by dotpointer** [comment]
@megheaiulian Feel free to jump into this branch (`gh38-1`) and edit it directly.

**Pull request merged**
